name: Base Two
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge
paginate: 3
gems: [jekyll-paginate]

authors:
  dmiller:
    name: Drew Miller
    email: dmiller@base2.io
    github: mewdriller
    gravatar: 9d45330e413884122510aa266ef6b7b7
  zbrown:
    name: Zack Brown
    email: zbrown@base2.io
    github: ztbrown015
    gravatar: 735b5104825b9a855e60cdc90792549e
  tborres:
    name: Tony Borres
    email: tborres@base2.io
    github: tborres
  jstevens:
    name: Jonathan Stevens
    email: jstevens@base2.io
    github: jonathanchris
  csteinert:
    name: Caitlin Steinert
    email: csteinert@base2.io
    github: csteinert
    gravatar: 429b5e0a56fc16d0aa349990d04200f5
  rdunkle:
    name: Reed Dunkle
    email: rdunkle@base2.io
    github: reeddunkle
