name: Base Two
markdown: redcarpet
pygments: false

assets:
  js_compressor: 'uglifier'
  css_compressor: 'sass'

  sources:
      - _assets/javascripts
      - _assets/stylesheets
      - _assets/images
      - _assets/fonts

  cachebust: soft
