backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "/static/img"
collections:
  - name: "settings"
    label: "Settings"
    delete: false
    editor:
      preview: false
    files:
      - name: "authors"
        label: "Authors"
        file: "_content/authors.yml"
        description: "Author descriptions"
        fields:
          - name: "authors"
            label: "Authors"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
  - name: "posts"
    label: "Posts"
    folder: "_content/posts"
    create: true
    slug: "{{year}}/{{month}}/{{day}}/{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: ["name"]
        valueField: "name"
